//! Autogenerated weights for pallet_kyc
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kico"), DB CACHE: 1024

// Executed Command:
// target/release/dico
// benchmark
// --chain=kico
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_kyc
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/pallet-weight-template.hbs
// --output
// ./pallets/kyc/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_kyc.
pub trait WeightInfo {
    fn set_kyc(r: u32, ) -> Weight;
    fn clear_kyc(r: u32, ) -> Weight;
    fn remove_kyc(r: u32, ) -> Weight;
    fn apply_certification(r: u32, ) -> Weight;
    fn add_ias(r: u32, ) -> Weight;
    fn add_sword_holder(r: u32, ) -> Weight;
    fn ias_set_fee(r: u32, ) -> Weight;
    fn sword_holder_set_fee(r: u32, ) -> Weight;
    fn kill_ias(r: u32, ) -> Weight;
    fn kill_sword_holder(r: u32, ) -> Weight;
    fn request_judgement(n: u32, ) -> Weight;
    fn ias_provide_judgement(n: u32, ) -> Weight;
    fn sword_holder_provide_judgement(n: u32, ) -> Weight;
}

/// Weights for pallet_kyc using the Substrate node and recommended hardware.
pub struct DicoWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for DicoWeight<T> {
    // Storage: Kyc BlackListOf (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn set_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc ApplicationFormList (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:1)
    fn clear_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc BlackListOf (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:0)
    // Storage: System Account (r:1 w:1)
    fn remove_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc BlackListOf (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc Nonce (r:1 w:1)
    // Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
    // Storage: Kyc IASListOf (r:1 w:0)
    // Storage: Kyc SwordHolderOf (r:1 w:0)
    fn apply_certification(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn add_ias(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)

    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn add_sword_holder(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    fn ias_set_fee(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    fn sword_holder_set_fee(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:1 w:0)
    fn kill_ias(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:1 w:0)
    fn kill_sword_holder(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    // Storage: Kyc MessageList (r:1 w:1)
    fn request_judgement(_n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    // Storage: Kyc UniqueIdOf (r:1 w:1)
    // Storage: Kyc MessageList (r:1 w:1)
    fn ias_provide_judgement(n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:0)
    // Storage: Kyc UniqueIdOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:3 w:3)
    // Storage: Kyc AreaData (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    fn sword_holder_provide_judgement(n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    // Storage: Kyc BlackListOf (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn set_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc ApplicationFormList (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:1)
    fn clear_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc BlackListOf (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:0)
    // Storage: System Account (r:1 w:1)
    fn remove_kyc(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc BlackListOf (r:1 w:0)
    // Storage: Kyc KYCOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc Nonce (r:1 w:1)
    // Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
    // Storage: Kyc IASListOf (r:1 w:0)
    // Storage: Kyc SwordHolderOf (r:1 w:0)
    fn apply_certification(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn add_ias(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn add_sword_holder(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    fn ias_set_fee(r: u32, ) -> Weight {
       Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    fn sword_holder_set_fee(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:1 w:0)
    fn kill_ias(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:1 w:0)
    fn kill_sword_holder(r: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    // Storage: Kyc MessageList (r:1 w:1)
    fn request_judgement(_n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc IASListOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    // Storage: Kyc UniqueIdOf (r:1 w:1)
    // Storage: Kyc MessageList (r:1 w:1)
    fn ias_provide_judgement(n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
    // Storage: Kyc SwordHolderOf (r:1 w:0)
    // Storage: Kyc UniqueIdOf (r:1 w:0)
    // Storage: Kyc ApplicationFormList (r:1 w:1)
    // Storage: Kyc KYCOf (r:1 w:1)
    // Storage: System Account (r:3 w:3)
    // Storage: Kyc AreaData (r:1 w:1)
    // Storage: Kyc RecordsOf (r:2 w:2)
    fn sword_holder_provide_judgement(n: u32, ) -> Weight {
        Weight::from_ref_time(20_0000_0000)
    }
}
