[profile.release]
panic = 'unwind'

[workspace]
members = [
#    'node/*',
    'pallets/*',
	'pallets/daos/*',
    'runtime/*',
    'primitives',
]
exclude = [
	'pallets/daos',
	'pallets/ico/rpc/*',
	'pallets/farm/rpc/*',
]
