[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node/*',
    'pallets/*',
	'pallets/ico/rpc/rpc',
	'pallets/farm/rpc',
	'pallets/daos/*',
    'runtime/*',
    'primitives',
]

exclude = [
	'pallets/daos',
]
