[profile.release]
panic = 'unwind'

[workspace]
members = [
#    'node/*',
    'pallets/*',
#	'pallets/daos/*',
#    'runtime/*',
    'primitives',
]
exclude = [
	'pallets/daos',
	'pallets/daos/*',
]
