[package]
name       = "pallet-dico-treasury"
authors    = ["DICO-TEAM"]
version    = "1.0.0"
license    = 'Apache 2.0'
homepage   = 'https://github.com/DICO-TEAM/dico-chain'
repository = 'https://github.com/DICO-TEAM/dico-chain'
edition    = '2018'


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
impl-trait-for-tuples = "0.2.1"
serde              = { version = "1.0.101", optional = true, features = ["derive"] }
codec              = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-std             = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false}
sp-runtime         = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false}
frame-support      = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false}
frame-system       = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false}
pallet-balances    = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false}
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false, optional = true }


# orml
orml-traits = { default-features = false, git = "https://github.com/open-web3-stack/open-runtime-module-library.git", rev = "650ef607d023e4537d3f2932baa5e50bc3a349cb"}

[dev-dependencies]
sp-io ={ version = "3.0.0"}
sp-core                                                = { version = "3.0.0" }
sp-storage                                             = { version = "3.0.0" }


[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"orml-traits/std",
	"frame-benchmarking/std",
#	"sp-io/std",
#	"sp-core/std",
#	"sp-storage/std",



]

#runtime-benchmarks = [
#	"frame-benchmarking",
#	"frame-support/runtime-benchmarks",
#	"frame-system/runtime-benchmarks",
#]
#try-runtime = ["frame-support/try-runtime"]
