
//! Autogenerated weights for `pallet_dao`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-26, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kico"), DB CACHE: 128

// Executed Command:
// ./target/release/dico
// benchmark
// --execution
// Wasm
// --wasm-execution
// compiled
// --pallet
// pallet_dao
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --raw
// --output
// ./pallets/dao/src/weights.rs
// --chain
// kico

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_dao`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dao::WeightInfo for WeightInfo<T> {
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao ProposalOf (r:1 w:1)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalCount (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	fn propose() -> Weight {
		(40_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao Voting (r:1 w:1)
	fn vote() -> Weight {
		(31_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Voting (r:1 w:1)
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:1 w:0)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn close() -> Weight {
		(31_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn disapprove_proposal() -> Weight {
		(16_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}
