//! Autogenerated weights for pallet_dao
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("tico"), DB CACHE: 128

// Executed Command:
// target/release/dico
// benchmark
// --chain=tico
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_dao
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/pallet-weight-template.hbs
// --output
// ./pallets/dao/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_dao.
pub trait WeightInfo {
	fn propose() -> Weight;
	fn vote() -> Weight;
	fn close() -> Weight;
	fn disapprove_proposal() -> Weight;
}

/// Weights for pallet_dao using the Substrate node and recommended hardware.
pub struct DicoWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for DicoWeight<T> {
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao ProposalOf (r:1 w:1)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalCount (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	fn propose() -> Weight {
		(66_688_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao Voting (r:1 w:1)
	fn vote() -> Weight {
		(53_239_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Voting (r:1 w:1)
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:1 w:0)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn close() -> Weight {
		(54_026_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn disapprove_proposal() -> Weight {
		(26_825_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao ProposalOf (r:1 w:1)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalCount (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	fn propose() -> Weight {
		(66_688_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao Voting (r:1 w:1)
	fn vote() -> Weight {
		(53_239_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Voting (r:1 w:1)
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:1 w:0)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn close() -> Weight {
		(54_026_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn disapprove_proposal() -> Weight {
		(26_825_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
}