//! Autogenerated weights for pallet_dao
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kico"), DB CACHE: 1024

// Executed Command:
// target/release/dico
// benchmark
// --chain=kico
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_dao
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=./.maintain/pallet-weight-template.hbs
// --output
// ./pallets/dao/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_dao.
pub trait WeightInfo {
	fn propose() -> Weight;
	fn vote() -> Weight;
	fn close() -> Weight;
	fn disapprove_proposal() -> Weight;
}

/// Weights for pallet_dao using the Substrate node and recommended hardware.
pub struct DicoWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for DicoWeight<T> {
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao ProposalOf (r:1 w:1)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalCount (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	fn propose() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao Voting (r:1 w:1)
	fn vote() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Dao Voting (r:1 w:1)
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:1 w:0)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn close() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn disapprove_proposal() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao ProposalOf (r:1 w:1)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalCount (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	fn propose() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:2 w:0)
	// Storage: Dao Voting (r:1 w:1)
	fn vote() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Dao Voting (r:1 w:1)
	// Storage: Ico Ico (r:1 w:0)
	// Storage: Ico UnReleaseAssets (r:1 w:0)
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn close() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
	// Storage: Dao Proposals (r:1 w:1)
	// Storage: Dao Voting (r:0 w:1)
	// Storage: Dao ProposalOf (r:0 w:1)
	fn disapprove_proposal() -> Weight {
		Weight::from_ref_time(20_0000_0000)
	}
}
