relaychain:
  image: parity/polkadot:v0.9.17
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_cooldown: 10
        validation_upgrade_delay: 10
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --execution=wasm
  nodes:
    - name: alice
      wsPort: 19944
      rpcPort: 19933
      port: 31333
    - name: bob
      wsPort: false
      rpcPort: false
      port: false

parachains:
  - image: dicoteam/dico
    chain:
      base: kico
      collators:
        - alice
      sudo: alice
    id: 2107
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --execution=wasm
    relaychainFlags:
      - --execution=wasm
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    nodes:
      - flags:
          - --alice
        wsPort: 19947
        rpcPort: 1996
        port: 31336
