relaychain:
  image: parity/polkadot:v0.9.13
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --ws-max-connections=4096
    - --force-authoring
    - --unsafe-pruning
    - --pruning=1000
    - --wasm-execution=compiled
    - --database=RocksDb
    - --state-cache-size=0
    - --execution=wasm
    - --no-telemetry
    - --no-beefy
  nodes:
    - name: alice
    - name: bob

parachains:
  - image: dicoteam/dico
    chain:
      base: tico
      collators:
        - alice
      sudo: alice
    id: 2000
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --rpc-cors=all
      - --ws-max-connections=4096
      - --force-authoring
      - --unsafe-pruning
      - --pruning=archive
      - --wasm-execution=compiled
      - --execution=wasm
      - --database=RocksDb
      - --state-cache-size=0
    relaychainFlags:
      - --rpc-methods=unsafe
      - --rpc-cors=all
      - --ws-max-connections=4096
      - --force-authoring
      - --unsafe-pruning
      - --ws-external
      - --rpc-external
      - --pruning=1000
      - --wasm-execution=compiled
      - --execution=wasm
      - --database=RocksDb
      - --state-cache-size=0
      - --execution=wasm
      - --no-telemetry
      - --no-beefy
    env:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
    nodes:
      - flags:
          - --alice