name: Srtool build

on:
  push:
    tags:
      - "v*"

jobs:
  srtool:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        chain: ["tico", "kico"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.4.0
        with:
          chain: ${{ matrix.chain }}
          runtime_dir: runtime/${{ matrix.chain }}
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
      - name: Install subwasm
        run: |
          wget https://github.com/chevdor/subwasm/releases/download/v0.16.1/subwasm_linux_amd64_v0.16.1.deb
          sudo dpkg -i subwasm_linux_amd64_v0.16.1.deb
          subwasm --version
      - name: Show Runtime information
        run: |
          subwasm info ${{ steps.srtool_build.outputs.wasm }}
          subwasm info ${{ steps.srtool_build.outputs.wasm_compressed }}
          subwasm --json info ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-info.json
          subwasm --json info ${{ steps.srtool_build.outputs.wasm_compressed }} > ${{ matrix.chain }}-info_compressed.json
      - name: Extract the metadata
        run: |
          subwasm meta ${{ steps.srtool_build.outputs.wasm }}
          subwasm --json meta ${{ steps.srtool_build.outputs.wasm }} > ${{ matrix.chain }}-metadata.json
      - name: Archive Runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime-${{ github.sha }}
          path: |
            ${{ matrix.chain }}-info.json
            ${{ matrix.chain }}-info_compressed.json
            ${{ matrix.chain }}-srtool-digest.json
            ${{ matrix.chain }}-metadata.json
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
      - name: Get Runtime Version
        if: startsWith(github.ref, 'refs/tags/')
        id: runtime_version
        run: echo ::set-output name=version::$(cat runtime/${{ matrix.chain }}/src/lib.rs | grep spec_version | tr -d ', ' | cut -d':' -f2)
      - name: Get Compressed Runtime Blake2-256 Hash
        if: startsWith(github.ref, 'refs/tags/')
        id: runtime_blake2_256_hash
        run: echo ::set-output name=hash::$(cat ${{ matrix.chain }}-info_compressed.json | jq '.blake2_256' -r)
      - name: Get GIT Tag
        if: startsWith(github.ref, 'refs/tags/')
        id: git_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@master
        with:
          files: |
            ${{ matrix.chain }}-info_compressed.json
            ${{ steps.srtool_build.outputs.wasm_compressed }}
          draft: false
          prerelease: false
          name: DICO ${{ steps.git_tag.outputs.tag }}
          append_body: true
          body: |
            `${{ matrix.chain }}_runtime-v${{ steps.runtime_version.outputs.version }}.compact.compressed.wasm - ${{ steps.runtime_blake2_256_hash.outputs.hash }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}