name: Test Code

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-code:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

      # Steps taken from https://github.com/actions/cache/blob/master/examples.md#rust---cargo
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}


    - name: Check Code
      run: cargo check

    - name: Test Code
      run: cargo test
